spring.application.name=service-persona
server.port=8011


#configuracion mysql
spring.datasource.url=jdbc:mysql://localhost:3307/personas_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver